version: '3.8'
services:
  postgres:
    container_name: serve-postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres  # Usuario por defecto
    ports:
      - "5432:5432"
    networks:
      - network_local_server
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "/home/ubuntu/db_backups:/backups/postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.corhuila.group=databases

volumes:
  postgres_data:
    driver: local

networks:
  network_local_server:
    external: true